# Generated by Django 5.1.1 on 2024-10-19 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_fname', models.CharField(max_length=50)),
                ('user_lanme', models.CharField(max_length=50)),
                ('user_email', models.EmailField(max_length=50)),
                ('user_phone', models.IntegerField()),
                ('user_pw', models.CharField(max_length=50)),
                ('user_loggedIn', models.BooleanField(default=False)),
            ],
        ),
    ]
