# Generated by Django 5.1.1 on 2024-10-19 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_portal_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_phone',
            field=models.CharField(max_length=12),
        ),
    ]
