# Generated by Django 5.1.2 on 2024-11-07 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_portal_app', '0004_rename_user_lanme_user_user_lname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptoms_list', models.CharField(max_length=50)),
            ],
        ),
    ]
