# Generated by Django 5.1.2 on 2024-11-10 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_portal_app', '0006_symptom_prescription_symptom_suggestions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='symptom',
            name='prescription',
        ),
        migrations.RemoveField(
            model_name='symptom',
            name='suggestions',
        ),
    ]
