# Generated by Django 5.1.2 on 2024-11-10 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_portal_app', '0007_remove_symptom_prescription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='symptom',
            name='prescription',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='symptom',
            name='suggestions',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
