# Generated by Django 5.1.2 on 2024-11-10 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_portal_app', '0008_symptom_prescription_symptom_suggestions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symptom',
            name='prescription',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='symptom',
            name='suggestions',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='symptom',
            name='symptoms_list',
            field=models.CharField(max_length=100),
        ),
    ]
