# Generated by Django 5.1.2 on 2024-11-12 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_portal_app', '0011_alter_appointments_user_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='user_appointment',
            field=models.CharField(max_length=50),
        ),
    ]
